---
# - name: add "stretch-backports" to sources (required for haproxy 1.8)
#   apt_repository:
#     repo: deb http://httpredir.debian.org/debian stretch-backports main
#     state: present
#     update_cache: yes

# - name: install haproxy
#   apt:
#     name: haproxy
#     state: present
#     default_release: stretch-backports
#     cache_valid_time: 3600

- name: install haproxy
  become: true
  become_method: sudo
  apt:
    pkg:
      - haproxy
    state: latest
    force_apt_get: true
    update_cache: yes

- name: check if the Certbot certificates exist
  stat:
    path: /opt/certbot/haproxy_fullchains/__fallback.pem
  register: certbot_cert_check_result

- name: copy haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify:
  - restart haproxy
